// LEVEL 1
Table items {
    id integer [primary key, increment]
    name varchar
    base_unit_id integer [ref: > units.id]
}

Table units {
    id integer [primary key, increment]
    name varchar
}

// LEVEL 2
Table stocks {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    quantity double
}

Table conversions {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    from_unit_id integer [ref: > units.id]
    to_unit_id integer [ref: > units.id]
    fraction double
}