// LEVEL 1
Table items {
    id integer [primary key, increment]
    name varchar
}

Table units {
    id integer [primary key, increment]
    name varchar
}

// LEVEL 2
Table stocks {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    unit_id integer [ref: > units.id]
    quantity double
}

Table convertibles {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    from_unit_id integer [ref: > units.id]
    to_unit_id integer [ref: > units.id]
    fraction double
    method varchar [note: 'split,merge']
}

// LEVEL 3
Table conversions {
    id integer [primary key, increment]
    from_stock_id integer [ref: > stocks.id]
    to_stock_id integer [ref: > stocks.id]
    fraction double
    method varchar [note: 'split,merge']
}