// LEVEL 1
Table items {
    id integer [primary key, increment]
    name varchar [unique]
}

Table locations {
    id integer [primary key, increment]
    name varchar [unique]
}

// LEVEL 2
Table stocks {
    id integer [primary key, increment]
    location_id integer [ref: > locations.id]
    item_id integer [ref: > items.id]
    min_quantity double
    max_quantity double
    quantity double
}

Table transfers {
    id integer [primary key, increment]
    location_id integer [ref: > locations.id, note: 'transfer source']
}

// LEVEL 3
Table transfer_items {
    id integer [primary key, increment]
    transfer_id integer [ref: > transfers.id]
    location_id integer [ref: > locations.id, note: 'transfer destination']
    item_id integer [ref: > items.id]
    quantity double
}