// LEVEL 1
Table items {
    id integer [primary key, increment]
    name varchar
}

Table units {
    id integer [primary key, increment]
    name varchar
    parent_unit_id integer [ref: > units.id]
    fraction double
}

// LEVEL 2
Table stocks {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    unit_id integer [ref: > units.id]
    quantity double
}

// LEVEL 3
Table conversions {
    id integer [primary key, increment]
    from_stock_id integer [ref: > stocks.id]
    to_stock_id integer [ref: > stocks.id]
    fraction double
    conversion_type varchar [note: 'value: split, merge']
}
