// LEVEL 1
Table items {
  id integer [primary key, increment]
  name varchar [unique]
}

// LEVEL 2
Table productions {
  id integer [primary key, increment]
  item_id integer [ref: > items.id]
  start_at datetime
  finished_at datetime
}

Table production_details {
  id integer [primary key, increment]
  production_id integer [ref: > productions.id]
  item_id integer [ref: > items.id]
  quantity double
  price double
}

Table processes {
  id integer [primary key, increment]
  item_id integer [ref: > items.id]
  parent_process_id integer [ref: > processes.id]
}