Table items {
    id integer [primary key, increment]
}

Table modifiers {
    id integer [primary key, increment]
    name varchar
    modifier_type varchar [note: 'percent,amount']
    value double
}

Table sales {
    id integer [primary key, increment]
}

Table item_modifiers {
    id integer [primary key, increment]
    item_id integer [ref: > items.id]
    
}

Table adjustments {
    id integer [primary key, increment]
    sale_id integer [ref: > sales.id]
    adjustable_type varchar
    adjustable_id varchar
    modifier_id integer [ref: > modifiers.id]
    value double
    amount double
}

Table sale_details {
    id integer [primary key, increment]
    sale_id integer [ref: > sales.id]
    item_id integer [ref: > items.id]
    quantity double
    price double
}

