//
// Level 1
//
Table tenants {
    id integer [primary key, increment]
    name varchar
    created_at datetime
    updated_at datetime
}

//
// Level 2
//
Table stores {
    id integer [primary key, increment]
    tenant_id integer [ref: > tenants.id]
    name varchar
    can_sell boolean
    created_at datetime
    updated_at datetime
}

Table users {
    id integer [primary key, increment]
    tenant_id integer [ref: > tenants.id]
    name varchar
    email varchar
    password varchar
    created_at datetime
    updated_at datetime
}

Table categories {
    id integer [primary key, increment]
    tenant_id integer [ref: > tenants.id]
    name varchar
    created_at datetime
    updated_at datetime
}

Table customers {
    id integer [primary key, increment]
    tenant_id integer [ref: > tenants.id]
    name varchar
    created_at datetime
    updated_at datetime
}

Table suppliers {
    id integer [primary key, increment]
    tenant_id integer [ref: > tenants.id]
    name varchar
    created_at datetime
    updated_at datetime
}

//
// Level 3
//
Table products {
    id integer [primary key, increment]
    category_id integer [ref: > categories.id]
    name varchar
    sku varchar
    price double
    stock double
    unit varchar
    created_at datetime
    updated_at datetime
}

//
// Level 4
//
Table stocks {
    id integer [primary key, increment]
    store_id integer [ref: > stores.id]
    product_id integer [ref: > products.id]
    quantity double
    unit varchar
    selling_price double
    created_at datetime
    updated_at datetime
}

//
// Level 5
//
Table sales {
    id integer [primary key, increment]
    store_id integer [ref: > stores.id]
    user_id integer [ref: > users.id]
    customer_id integer [ref: > customers.id]
    sold_at datetime
    created_at datetime
    updated_at datetime
}

Table purchases {
    id integer [primary key, increment]
    store_id integer [ref: > stores.id]
    user_id integer [ref: > users.id]
    supplier_id integer [ref: > suppliers.id]
    sold_at datetime
    created_at datetime
    updated_at datetime
}

Table transfers {
    id integer [primary key, increment]
    from_store_id integer [ref: > stores.id]
    to_store_id integer [ref: > stores.id]
    user_id integer [ref: > users.id]
    sent_at datetime [null]
    received_at datetime [null]
    created_at datetime
    updated_at datetime
}

//
// Level 6
//
Table sale_details {
    id integer [primary key, increment]
    sale_id integer [ref: > sales.id]
    stock_id integer [ref: > stocks.id]
    quantity double
    price double
}

Table purchase_details {
    id integer [primary key, increment]
    purchase_id integer [ref: > purchases.id]
    stock_id integer [ref: > stocks.id]
    quantity double
    price double
}

Table transfer_details {
    id integer [primary key, increment]
    transfer_id integer [ref: > transfers.id]
    stock_id integer [ref: > stocks.id]
    quantity double
    unit varchar
}