Table users {
  id integer [primary key, increment]
  name varchar
  email varchar [unique]
  password varchar
  created_at datetime
  updated_at datetime
}

Table products {
  id integer [primary key, increment]
  name varchar [unique]
  description text
  price double
  created_at datetime
  updated_at datetime
}

Table sales {
  id integer [primary key, increment]
  user_id integer [ref: > users.id]
  sold_at datetime
  created_at datetime
  updated_at datetime
}

Table sale_details {
  id integer [primary key, increment]
  sale_id integer [ref: > sales.id]
  product_id integer [ref: > products.id]
  quantity double
  price double
}