Table costs {
  id integer [primary key, increment]
  cost_type varchar [note: 'sale, purchase, production']
  name varchar [unique]
  price double
  created_at datetime
  updated_at datetime
}

Table items {
  id integer [primary key, increment]
  name varchar [unique]
  can_be_sold boolean
  can_be_purchased boolean
  quantity double
  created_at datetime
  updated_at datetime
}

Table productions {
  id integer [primary key, increment]
  item_id integer [ref: > items.id]
  start_at datetime
  finished_at datetime
  created_at datetime
  updated_at datetime
}

Table production_details {
  id integer [primary key, increment]
  production_id integer [ref: > productions.id]
  item_id integer [ref: > items.id]
  quantity double
  price double
}

Table sales {
  id integer [primary key, increment]
  sold_at datetime
  created_at datetime
  updated_at datetime
}

Table sale_details {
  id integer [primary key, increment]
  sale_id integer [ref: > sales.id]
  item_id integer [ref: > items.id]
  quantity double
  price double
}

Table purchases {
  id integer [primary key, increment]
  purchased_at datetime
  created_at datetime
  updated_at datetime
}

Table purchase_details {
  id integer [primary key, increment]
  purchase_id integer [ref: > purchases.id]
  item_id integer [ref: > items.id]
  quantity double
  price double
}