// LEVEL 1
Table subscriptions {
    id integer [primary key, increment]
    subscriber_id integer [note: 'subscribing party']
    subscriber_type varchar
    subscribable_id integer [note: 'something to subscribed to']
    subscribable_type varchar
    subscription_type subscription_type
    subscribed_at datetime
    started_at datetime
    end_at datetime
    subscription_status subscription_status
}

// LEVEL 2
Table invoices {
    id integer [primary key, increment]
    subscription_id integer [ref: > subscriptions.id]
    issued_date date
    due_date date
    amount double
}

Table upgrades {
    id integer [primary key, increment]
    upgrader_id integer
    upgradable_id integer [ref: > subscriptions.id]
    upgraded_id integer [ref: > subscriptions.id]
}

// LEVEL 3
Table payments {
    id integer [primary key, increment]
    invoice_id integer [ref: > invoices.id]
    paid_at datetime
    method varchar
    amount double
    status payment_status
}

// ENUM
Enum subscription_type {
    one_time
    auto_renew
    prepaid
}

Enum subscription_status {
    active
    suspended [note: 'terminated by system']
    cancelled [note: 'terminated by user']
    expired
    grace_period
    upgraded
}

Enum payment_status {
    paid
    unpaid
    pending
    expired
}
